spring.application.name=springDemo

# fornisco a Spring la URL JDBC per connettersi al DB
# la connessione tramite driver JDBC (fornito nel pom) e' in carico a SpringBoot
# non bisogna scrivere ulteriore codice

spring.datasource.url = jdbc:mysql://localhost:3306/bookstore
spring.datasource.username = root
spring.datasource.password = password

# con questa property, Hibernate, tramite ORM (Object Relational Mapping)
# interviene direttamente sul DB ogni volta che una Entity viene creata / modificata

spring.jpa.hibernate.ddl-auto = update